/**
 * Canonical editing skill registry — execution reality + product gaps.
 * Director receives this; cannot invent unsupported executable skills.
 */

import type { EditingSkillV1 } from "./types";

export function buildEditingSkillRegistryV1(): EditingSkillV1[] {
	return [
		{
			skill: "TRIM",
			intentKinds: ["REMOVE_DEAD_TIME", "TIGHTEN_SECTION"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["dead_air", "speech_boundaries"],
			groundingStrategy: "deadAir + keepPause + visual safety",
			verificationStrategy: "applyPreview family verify + final sequence join",
			conflicts: ["must_survive_speech"],
			preservationRules: ["KEEP_SOME_PAUSE", "never_cut_inside_word"],
			rendererRequirements: ["timeline.trimRanges"],
			chatAvailable: true,
			operations: ["add", "adjust", "remove"],
			acceptedTargetTypes: ["EXPLICIT_RANGE", "SEMANTIC_EVENT", "WHOLE_PROGRAMME", "PREVIOUS_EDIT"],
			modificationOps: ["shorter", "longer", "earlier", "later"],
			evidenceKinds: ["transcript", "visual", "document"],
			directEntry: "localEditorialChat/directTrim",
			autonomousEntry: "professionalEditOrchestrator/deadAir",
			acceptsSemanticTarget: true,
		},
		{
			skill: "ZOOM",
			intentKinds: ["EMPHASIZE_TARGET"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["cursor_focal", "editorial_usefulness"],
			groundingStrategy: "EditorialFocalEvidence geometry + planner usefulness",
			verificationStrategy: "applyPreview / editVerify zoom",
			conflicts: ["webcam_near_target", "ambiguous_focal"],
			preservationRules: ["no_invented_focus"],
			rendererRequirements: ["zoomRanges"],
			chatAvailable: true,
			operations: ["add", "adjust", "remove"],
			acceptedTargetTypes: [
				"EXPLICIT_RANGE",
				"SEMANTIC_EVENT",
				"PREVIOUS_EDIT",
				"PENDING_PROPOSAL",
				"SELECTION",
			],
			modificationOps: ["stronger", "weaker", "earlier", "later"],
			evidenceKinds: ["cursor", "transcript", "visual", "document"],
			directEntry: "localEditorialChat/directZoomFocus",
			autonomousEntry: "professionalEditOrchestrator/focal",
			acceptsSemanticTarget: true,
		},
		{
			skill: "CROP_REFRAME",
			intentKinds: ["REFRAME_SCENE"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["measured_framing_geometry"],
			groundingStrategy: "explicit framingCrop only — no speculative geometry",
			verificationStrategy: "applyPreview / editVerify crop",
			conflicts: ["fullscreen_already_framed"],
			preservationRules: ["protected_regions_visible"],
			rendererRequirements: ["clip.cropRegion"],
			notes: "Often HONESTLY_LIMITED without measured unused-canvas geometry",
		},
		{
			skill: "SPEED_UP",
			intentKinds: ["ACCELERATE_LOW_INFORMATION_SECTION"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["stable_visual_span", "low_speech_overlap"],
			groundingStrategy: "planner speed rates 1.25/1.5/2",
			verificationStrategy: "applyPreview speed + final sequence SPEED_BOUNDARY",
			conflicts: ["important_action", "dense_narration", "grounded_focal"],
			preservationRules: ["never_speed_protected_speech"],
			rendererRequirements: ["speedRanges"],
			chatAvailable: true,
			operations: ["add", "adjust", "remove"],
			acceptedTargetTypes: ["EXPLICIT_RANGE", "SEMANTIC_EVENT", "PREVIOUS_EDIT", "WHOLE_PROGRAMME"],
			modificationOps: ["faster", "slower"],
			evidenceKinds: ["transcript", "visual", "document"],
			directEntry: "localEditorialChat/directSpeed",
			autonomousEntry: "professionalEditOrchestrator/plan",
			acceptsSemanticTarget: true,
		},
		{
			skill: "SLOW_MOTION",
			intentKinds: ["SLOW_IMPORTANT_ACTION"],
			classification: "EXECUTION_ONLY",
			supported: true,
			executionReady: true,
			requiredEvidence: ["important_action_span"],
			groundingStrategy: "not generated autonomously in V1",
			verificationStrategy: "applyPreview speed if rate<1",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: ["speedRanges"],
			productGapRank: 6,
			notes: "addSpeed accepts <1; no autonomous slow-down generator",
		},
		{
			skill: "CAPTIONS",
			intentKinds: ["ADD_CAPTIONS"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["transcript"],
			groundingStrategy: "captionLayout",
			verificationStrategy: "caption layout verify + final sequence caption continuity",
			conflicts: ["manual_caption_conflict"],
			preservationRules: ["preserve_manual_captions"],
			rendererRequirements: ["caption settings + cues"],
			chatAvailable: true,
			operations: ["add", "adjust", "remove"],
			acceptedTargetTypes: ["WHOLE_PROGRAMME", "EXPLICIT_RANGE", "PREVIOUS_EDIT"],
			modificationOps: ["smaller", "larger", "higher", "lower", "text"],
			evidenceKinds: ["transcript", "document"],
			directEntry: "localEditorialChat/directCaptions",
			autonomousEntry: "professionalEditOrchestrator/captions",
			acceptsSemanticTarget: false,
		},
		{
			skill: "LOUDNESS",
			intentKinds: ["BALANCE_AUDIO"],
			classification: "PARTIAL",
			supported: true,
			executionReady: true,
			requiredEvidence: ["loudness_analysis"],
			groundingStrategy: "loudnessCoord settings path (not ApplyPreview)",
			verificationStrategy: "loudness verify module",
			conflicts: [],
			preservationRules: ["peak_limited"],
			rendererRequirements: ["legacyEditor.audioGainDb"],
		},
		{
			skill: "PAN_CAMERA",
			intentKinds: ["EMPHASIZE_TARGET"],
			classification: "PARTIAL",
			supported: false,
			executionReady: false,
			requiredEvidence: ["motion_path"],
			groundingStrategy: "none — zoom focus is closest",
			verificationStrategy: "none",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: [],
			productGapRank: 3,
			notes: "No dedicated pan tool; zoom focus is partial substitute",
		},
		{
			skill: "TRANSITIONS",
			intentKinds: ["ADD_TRANSITION"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["multi_clip_join", "story_boundary"],
			groundingStrategy:
				"setClipIncomingTransition on non-first clip; CUT default, DISSOLVE only when target story wants it",
			verificationStrategy: "applyPreview transition identity verify",
			conflicts: ["single_clip_programme"],
			preservationRules: ["no_dissolve_quota"],
			rendererRequirements: ["clip.incomingTransition → SceneClip.incomingFadeHalfSec"],
			notes: "Authorable CUT|DISSOLVE; single-clip tutorials correctly skip",
			chatAvailable: true,
			operations: ["add", "adjust", "remove", "list"],
			acceptedTargetTypes: ["EXPLICIT_RANGE", "PREVIOUS_EDIT", "WHOLE_PROGRAMME", "SEMANTIC_EVENT"],
			modificationOps: ["shorter", "longer", "to_cut", "to_dissolve"],
			evidenceKinds: ["story", "document", "visual"],
			directEntry: "localEditorialChat/directTransition",
			autonomousEntry: "transitionLibrary/autonomousIntelligence",
			acceptsSemanticTarget: true,
		},
		{
			skill: "TITLES_CALLOUTS",
			intentKinds: ["ADD_TITLE", "ADD_CALLOUT"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["beat_purpose", "focal_or_speech"],
			groundingStrategy: "planner title from speech/story; callout from grounded focal",
			verificationStrategy: "applyPreview graphicVerify + compositor frames",
			conflicts: ["existing_manual_annotations"],
			preservationRules: ["no_invented_geometry", "no_creative_rewrite"],
			rendererRequirements: ["annotations / graphicPlate"],
			chatAvailable: true,
			operations: ["add", "adjust", "remove"],
			acceptedTargetTypes: ["EXPLICIT_RANGE", "SEMANTIC_EVENT", "PREVIOUS_EDIT", "WHOLE_PROGRAMME"],
			modificationOps: ["text", "bigger", "smaller", "earlier", "later"],
			evidenceKinds: ["transcript", "cursor", "story", "document"],
			directEntry: "localEditorialChat/directTitle|directCallout",
			autonomousEntry: "professionalEditOrchestrator/plan",
			acceptsSemanticTarget: true,
		},
		{
			skill: "ANIMATIONS",
			intentKinds: ["ADD_TITLE"],
			classification: "EXECUTION_ONLY",
			supported: true,
			executionReady: true,
			requiredEvidence: [],
			groundingStrategy: "textAnimation on annotations only",
			verificationStrategy: "none",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: ["textAnimation"],
			productGapRank: 8,
		},
		{
			skill: "COLOR_GRADE",
			intentKinds: ["IMPROVE_COLOR"],
			classification: "MISSING",
			supported: false,
			executionReady: false,
			requiredEvidence: ["frame_stats"],
			groundingStrategy: "unsupported",
			verificationStrategy: "none",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: [],
			productGapRank: 4,
		},
		{
			skill: "AUDIO_CLEANUP",
			intentKinds: ["AUDIO_CLEANUP"],
			classification: "MISSING",
			supported: false,
			executionReady: false,
			requiredEvidence: ["noise_profile"],
			groundingStrategy: "unsupported (denoise:false)",
			verificationStrategy: "none",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: [],
			productGapRank: 5,
		},
		{
			skill: "HIGHLIGHTS",
			intentKinds: ["EMPHASIZE_TARGET", "ADD_CALLOUT"],
			classification: "FULL_AUTONOMOUS_PATH",
			supported: true,
			executionReady: true,
			requiredEvidence: ["grounded_focal"],
			groundingStrategy: "callout via addGraphic figure from focal geometry",
			verificationStrategy: "applyPreview graphicVerify",
			conflicts: [],
			preservationRules: ["no_invented_geometry"],
			rendererRequirements: ["annotations"],
		},
		{
			skill: "BACKGROUND_CANVAS",
			intentKinds: [],
			classification: "EXECUTION_ONLY",
			supported: true,
			executionReady: true,
			requiredEvidence: [],
			groundingStrategy: "setBackground agent tool only",
			verificationStrategy: "none",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: ["wallpaper"],
			productGapRank: 9,
		},
		{
			skill: "WEBCAM_PIP",
			intentKinds: [],
			classification: "EXECUTION_ONLY",
			supported: true,
			executionReady: true,
			requiredEvidence: ["hasCameraTrack"],
			groundingStrategy: "addCameraFullscreen — not autonomous",
			verificationStrategy: "none",
			conflicts: [],
			preservationRules: [],
			rendererRequirements: ["cameraFullscreenRegions"],
			productGapRank: 10,
		},
	];
}

export function executableSkills(registry: EditingSkillV1[]): EditingSkillV1[] {
	return registry.filter((s) => s.supported && s.executionReady);
}

export function chatAvailableSkills(registry: EditingSkillV1[]): EditingSkillV1[] {
	return registry.filter((s) => s.chatAvailable === true && s.supported && s.executionReady);
}

export function productCapabilityGaps(registry: EditingSkillV1[]): EditingSkillV1[] {
	return registry
		.filter((s) => s.classification === "MISSING" || s.productGapRank != null)
		.sort((a, b) => (a.productGapRank ?? 99) - (b.productGapRank ?? 99));
}

/** Compact descriptors for the semantic understanding brain (no HOW logic). */
export function skillDescriptorsForBrain(registry?: EditingSkillV1[]): Array<{
	skill: string;
	operations: string[];
	acceptedTargetTypes: string[];
	acceptsSemanticTarget: boolean;
	modificationOps: string[];
}> {
	const skills = chatAvailableSkills(registry ?? buildEditingSkillRegistryV1());
	return skills.map((s) => ({
		skill: s.skill,
		operations: s.operations ?? [],
		acceptedTargetTypes: s.acceptedTargetTypes ?? [],
		acceptsSemanticTarget: Boolean(s.acceptsSemanticTarget),
		modificationOps: s.modificationOps ?? [],
	}));
}
